orders:
  none:
    type: unit_state_transform
    transform_to: none
  go:
    type: action
  fortify:
    type: unit_state_transform
    transform_to: fortified
  siege:
    type: unit_state_transform
    transform_to: siege_mode
  build_road:
    type: construction
    structure: road
  build_fortress:
    type: construction
    structure: fortress
  build_city:
    type: construction
    structure: city
  build_farm:
    type: construction
    structure: farm
units:
  infantry:
    movement: 
      base: 2
    allowed_orders:
      - none
      - go
      - fortify
      - siege
  worker:
    movement: 
      base: 4
    allowed_orders:
      - none
      - go
      - build_road
      - build_fortress
      - build_farm
      - build_city
  tank:
    movement: 
      base: 2
      penalty_terrain: 
        marsh: null
        forest: 4
    allowed_orders:
      - none
      - go
      - fortify
      - siege
  ship:
    movement:
      base: 6
    allowed_orders:
      - none
      - go
terrain:
  grass:
    type: land
    move_cost: 1
    fortification_bonus: 2
  plains:
    type: land
    move_cost: 1
    fortification_bonus: 2
  desert:
    type: land
    move_cost: 1
    fortification_bonus: 1.5
  forest:
    type: land
    move_cost: 2
    fortification_bonus: 3
  marsh:
    type: land
    move_cost: 2
    fortification_bonus: null
  hill:
    type: land
    move_cost: 2
    fortification_bonus: 2
  mountains:
    type: land
    move_cost: null
    fortification_bonus: null
  water:
    type: water
    move_cost: 1
    fortification_bonus: null
structures:
  road:
    time_cost: 2
  fortress:
    time_cost: 8
  farm:
    time_cost: 3
  city:
    time_cost: 1